cluster_name: default

# cassandra version
cassandra_version: 3.11.5
# http://mirrors.tuna.tsinghua.edu.cn/apache/cassandra/3.11.5/apache-cassandra-3.11.5-bin.tar.gz
cassandra_download_dir: "{{ ansible_temp_dir }}"
cassandra_release: "apache-cassandra-{{ cassandra_version }}-bin.tar.gz"
cassandra_targz_file: "{{ cassandra_download_dir }}/{{ cassandra_release }}"
cassandra_download_url: "http://mirrors.tuna.tsinghua.edu.cn/apache/cassandra/{{ cassandra_version }}/{{ cassandra_release }}"
cassandra_unarchived_dir: "{{ cassandra_download_dir }}/apache-cassandra-{{ cassandra_version }}"
#Directory locations
cassandra_home: /data/cassandra
cassandra_install_dir: "{{ cassandra_home }}"
cassandra_path: "{{ cassandra_home }}/bin"
cassandra_data_dir: "{{ cassandra_home }}/data"
cassandra_hints_dir: "{{ cassandra_home }}/data/hints"
cassandra_commitlog_dir: "{{ cassandra_home }}/data/commitlogs"
cassandra_saved_caches_dir: "{{ cassandra_home }}/data/saved_caches"
#For IP Address configuration in YML
cassandra_seeds_resolved: "{{ groups['cassandra_seeds'] | map('extract', hostvars, ['host_ip_address']) | join(',') }}"
broadcast_address: "{{ hostvars[inventory_hostname]['host_ip_address'] }}"
listen_address: "{{ hostvars[inventory_hostname]['host_ip_address'] }}"
broadcast_rpc_address: "{{ hostvars[inventory_hostname]['host_ip_address'] }}"
#Port configurations
cassandra_port: 9042
rpc_port: 9160
storage_port: 7000
ssl_storage_port: 7001
# cassandra user group
cassandra_group: cassandra
cassandra_user: cassandra
cassandra_user_home_dir: /home/cassandra