---

cassandra_cluster_name: cassandra-jpw 
# For workloads with more data than can fit in memory, Cassandra's
# bottleneck will be reads that need to fetch data from
# disk. "concurrent_reads" should be set to (16 * number_of_drives) in
# order to allow the operations to enqueue low enough in the stack
# that the OS and drives can reorder them. Same applies to
# "concurrent_counter_writes", since counter writes read the current
# values before incrementing and writing them back.
# 
# On the other hand, since writes are almost never IO bound, the ideal
# number of "concurrent_writes" is dependent on the number of cores in
# your system; (8 * number_of_cores) is a good rule of thumb.
cassandra_concurrent_reads: 64
cassandra_concurrent_writes: 64
cassandra_concurrent_counter_writes: 64
# cassandra endpoint_snitch
# SimpleSnitch  GossipingPropertyFileSnitch
endpoint_snitch: SimpleSnitch

cassandra_dc: opp-jpw
cassandra_rack: opp-jpw