---

- hosts: prometheus
  become: yes
  roles:
     - role: prometheus/prometheus
  tags:
     - prometheus

- hosts: "{{ variable_host | default('linux') }}"
  become: yes
  roles:
     - role: prometheus/exporters/node-exporter
  tags:
     - node-exporter


- hosts: prometheus
  become: yes
  roles:
     - role: prometheus/grafana
  tags:
     - grafana
     
- hosts: mysql
  become: yes
  roles:
     - role: prometheus/exporters/mysqld-exporter
  tags:
     - mysqld-exporter

