

- name: ensure install dirs
  file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode: 0750
  with_items:
    - "{{ cassandra_install_dir }}"  
    - "{{ cassandra_data_dir }}" 

- name: install java
  yum:
    name: java
    state: present 

- name: unarchive install
  unarchive: 
    src: "{{ cassandra_targz_file }}"
    dest: "{{ cassandra_install_dir }}"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    extra_opts: [--strip-components=1]
    remote_src: yes   

- name: set dc information
  lineinfile:
    path: "{{ cassandra_install_dir}}/conf/cassandra-rackdc.properties"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - regexp: '^dc=.*?'
      line: 'dc={{cassandra_dc}}'
    - regexp: '^rack=.*?'
      line: 'rack={{cassandra_rack}}'
- name: set cassandra home env
  lineinfile: 
    dest: /etc/profile 
    regexp: '^export CASSANDRA_HOME=.*?$'
    line: "export CASSANDRA_HOME={{ cassandra_install_dir }}" 
    state: present

- name: export cassandra bin to path
  lineinfile: 
    dest: /etc/profile 
    regexp: '^export PATH=\$PATH:\$CASSANDRA_HOME/bin$'
    line: "export PATH=$PATH:$CASSANDRA_HOME/bin" 
    state: present

- name: copy conf
  template: 
    src: cassandra.yml.j2
    dest: "{{ cassandra_install_dir }}/conf/cassandra.yaml"
    
- name: copy systemd unit
  template: 
    src: cassandra.service.j2
    dest: /etc/systemd/system/cassandra.service
