---
- name: set hosts
  lineinfile: 
    dest: /etc/hosts 
    regexp: '{{ item.regexp }}'
    line: "{{ item.line }}" 
    state: present
  with_items: "{{ centos_hosts }}"
  tags:
     - sethosts
  

  

  
