---

- name: create bucket Ansible with 2 replicas

shell: /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091  --bucket={{ bucket }} --bucket-type=couchbase --bucket-port=11222 --bucket-ramsize={{ bucket_ram }}  --bucket-replica={{ replicas }} -u {{ user }} -p {{ password }}
