---

- name: config disable selinux
  lineinfile: 
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'
    
- name: diable selinux
  selinux: 
    state: disabled

- name: Stop and disabled service firewalld 
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: "'firewalld.service' in ansible_facts.services"
