---


- name: pam limits nofile
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - domain: "*"
      limit_type: soft
      limit_item: "nofile"
      value: 65535
    - domain: "*"
      limit_type: hard
      limit_item: "nofile"
      value: 65535 

- name: sysctl 
  sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - name: fs.file-max
      value: 262144
    - name: vm.swappiness
      value: 0



  

  
