---

- name: ensure download dir
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prometheus_download_dir }}"  
    
- name: check whether prometheus downloaded
  stat: 
    path: "{{ prometheus_targz_file }}"
  register: prometheus_downloaded_check
  
- name: download prometheus
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: "{{ prometheus_download_dir }}"
    validate_certs: no
    timeout: 120
  when: not prometheus_downloaded_check.stat.exists
  
- name: check whether prometheus unarchived
  stat: 
    path: "{{ prometheus_unarchived_dir }}"
  register: prometheus_unarchived_check

- name: unarchive prometheus targz
  unarchive: 
    src: "{{ prometheus_targz_file }}"
    dest: "{{ prometheus_download_dir }}"
    remote_src: yes
  when: not prometheus_unarchived_check.stat.exists