

- name: ensure install dirs
  file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0750
  with_items:
    - "{{ prometheus_install_dir }}"  
    - "{{ prometheus_data_dir }}" 
    - "{{ prometheus_rule_files_dir }}" 
    

- name: unarchive install
  unarchive: 
    src: "{{ prometheus_targz_file }}"
    dest: "{{ prometheus_install_dir }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    extra_opts: [--strip-components=1]
    remote_src: yes
    
- name: chmod bin
  file: 
    path: "{{ prometheus_install_dir }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0750
  with_items:
    - prometheus
    - promtool
    

- name: copy conf
  template: 
    src: prometheus.yml.j2
    dest: "{{ prometheus_install_dir }}/prometheus.yml"
    
- name: check conf
  command: "{{ prometheus_install_dir }}/promtool check config {{ prometheus_install_dir }}/{{ item }}"
  with_items:
    - prometheus.yml
    
- name: copy systemd unit
  template: 
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
